import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Amiseungyo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        {/* 폰트 최적화를 위한 preconnect 링크 */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Google Fonts 링크 */}

        <link
          href="https://fonts.googleapis.com/css2?family=Acme&family=Do+Hyeon&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
